### ISSUE TITLE
CI Fails with Error: ENOENT: no such file or directory './.github/workflows/run-commands-in-parallel.sh'

### ISSUE THREAD

**Issue by Sagato** [nrwl/ci#15]
I am using the ci template to get initial out of the box CI with nx cloud.
I am getting this error since 2 days. 

If I understand correctly it is a script generated by the workflow itself. Is this known?

```[Nx Cloud - Main Job / Run](https://github.com/Cheveo/gymony/runs/6592554030?check_suite_focus=true#logs)
failed 12 minutes ago in 1m 26s
Search logs
4s
2s
0s
0s
0s
1s
0s
0s
4s
0s
0s
0s
0s
1m 9s
0s
##[debug]Evaluating condition for step: 'Create command utils'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Create command utils
##[debug]Loading inputs
##[debug]Evaluating: github.token
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'token'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Run actions/github-script@v6
  with:
    script: const { writeFileSync } = require('fs');
  const runCommandsInParallelScript = `
    # Extract the provided commands from the stringified JSON array.
    IFS=$'\n' read -d '' -a userCommands < <((jq -c -r '.[]') <<<"$[1](https://github.com/Cheveo/gymony/runs/6592554030?check_suite_focus=true#step:15:1)")
  
    # Invoke the provided commands in parallel and collect their exit codes.
    pids=()
    for userCommand in "\${userCommands[@]}"; do
      eval "$userCommand" & pids+=($!)
    done
  
    # If any one of the invoked commands exited with a non-zero exit code, exit the whole thing with code 1.
    for pid in \${pids[*]}; do
      if ! wait $pid; then
        exit 1
      fi
    done
  
    # All the invoked commands must have exited with code zero.
    exit 0
  `;
  writeFileSync('./.github/workflows/run-commands-in-parallel.sh', runCommandsInParallelScript);
  
    github-token: ***
    debug: false
    user-agent: actions/github-script
    result-encoding: json
  env:
    NX_CLOUD_DISTRIBUTED_EXECUTION: true
    NX_BRANCH: 8
    NX_BASE: a98c3111c1719c38b639b69a9811e49f373361ea
    NX_HEAD: 6accfdaef9a5fb6[2](https://github.com/Cheveo/gymony/runs/6592554030?check_suite_focus=true#step:15:2)d9c621e[3](https://github.com/Cheveo/gymony/runs/6592554030?check_suite_focus=true#step:15:3)07b85[4](https://github.com/Cheveo/gymony/runs/6592554030?check_suite_focus=true#step:15:4)d[5](https://github.com/Cheveo/gymony/runs/6592554030?check_suite_focus=true#step:15:5)1829cdce
    VOLTA_HOME: /opt/hostedtoolcache/volta/1.0.7/x[6](https://github.com/Cheveo/gymony/runs/6592554030?check_suite_focus=true#step:15:6)4
Error: ENOENT: no such file or directory, open './.github/workflows/run-commands-in-parallel.sh'
    at Object.openSync (node:fs:585:3)
    at writeFileSync (node:fs:2153:35)
    at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:480[7](https://github.com/Cheveo/gymony/runs/6592554030?check_suite_focus=true#step:15:7):16), <anonymous>:24:1)
    at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:4[8](https://github.com/Cheveo/gymony/runs/6592554030?check_suite_focus=true#step:15:8)08:12)
    at main (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:4862:26)
    at Module.272 (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:4846:1)
    at __webpack_require__ (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:24:31)
    at startup (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:43:1[9](https://github.com/Cheveo/gymony/runs/6592554030?check_suite_focus=true#step:15:9))
    at /home/runner/work/_actions/actions/github-script/v6/dist/index.js:49:18
    at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:52:[10](https://github.com/Cheveo/gymony/runs/6592554030?check_suite_focus=true#step:15:10)) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './.github/workflows/run-commands-in-parallel.sh'
}
Error: Unhandled error: Error: ENOENT: no such file or directory, open './.github/workflows/run-commands-in-parallel.sh'
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Create command utils```

**Comment by meeroslav** [comment]
Hey @Sagato,

Is this still an issue?

**Comment by Sagato** [comment]
No, thx. I do not use it anymore. Regards
