### ISSUE TITLE
Usage with act?

### ISSUE THREAD

**Issue by leggomuhgreggo** [nrwl/ci#39]
## Overview

I was wondering if it's possible to use Nx actions locally with [act](https://github.com/nektos/act).

## Errors

<details>
  <summary>Error</summary>
  
```shell
[CI/main]   ✅  Success - Main Checkout
[CI/main] ⭐ Run Main Set NX SHAs
[CI/main]   🐳  docker cp src=/Users/UserName/.cache/act/nrwl-nx-set-shas@v3/ dst=/var/run/act/actions/nrwl-nx-set-shas@v3/
[CI/main] ⭐ Run Main Set base and head SHAs used for nx affected
[CI/main]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/1-composite-setSHAs.sh] user= workdir=
[CI/main]   ❗  ::error::Not Found
[CI/main]   ❌  Failure - Main Set base and head SHAs used for nx affected
```

</details>

First issue was something to do with the work directory

Looked at the GH and tried [this fix](https://github.com/nektos/act#known-issues)
```
steps:
  - name: Checkout
    uses: actions/checkout@v2
    with:
      path: "my-action"
```      

Then I got this "not a git repository" error

<details>
  <summary>Error</summary>
  
  ```shell
[CI/main] ⭐ Run Main Set base and head SHAs used for nx affected
[CI/main]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/1-composite-setSHAs.sh] user= workdir=
| fatal: not a git repository (or any parent up to mount point /Users/UserName/projects/personal)
| Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
| node:internal/errors:857
|   const err = new Error(message);
|               ^
| 
| Error: Command failed: git rev-parse HEAD
| fatal: not a git repository (or any parent up to mount point /Users/UserName/projects/personal)
| Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
| 
|     at checkExecSyncError (node:child_process:861:11)
|     at execSync (node:child_process:932:15)
|     at /run/act/actions/nrwl-nx-set-shas@v3/dist/index.js:13735:20
|     at /run/act/actions/nrwl-nx-set-shas@v3/dist/index.js:13771:3
|     at /run/act/actions/nrwl-nx-set-shas@v3/dist/index.js:13846:3
|     at Object.<anonymous> (/run/act/actions/nrwl-nx-set-shas@v3/dist/index.js:13849:12)
|     at Module._compile (node:internal/modules/cjs/loader:1155:14)
|     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
|     at Module.load (node:internal/modules/cjs/loader:1033:32) {
|   status: 128,
|   signal: null,
|   output: [
|     null,
|     '',
|     'fatal: not a git repository (or any parent up to mount point /Users/UserName/projects/personal)\n' +
|       'Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).\n'
|   ],
|   pid: 34,
|   stdout: '',
|   stderr: 'fatal: not a git repository (or any parent up to mount point /Users/UserName/projects/personal)\n' +
|     'Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).\n'
| }

  ```
</details>

That's where I paused and figured I'd ask to see if anyone has tried this. 

Thanks!

**Comment by meeroslav** [comment]
This question is probably best directed at `act` creators. Based on your error message it seems that the docker image doesn't get the full git history so running `git rev-parse HEAD` fails.

Is your project at `/Users/UserName/projects/personal`? Perhaps you are running the command on the wrong folder.

**Comment by LayZeeDK** [comment]
Act [does not support reusable workflows](https://github.com/nektos/act/issues/826) yet.

**Comment by JamesHenry** [comment]
As noted by @LayZeeDK this is not something which is possible, nor something we can influence, so closing this one
